---
- name: Elasticsearch | Install and configure Elasticsearch
  block:
    - name: Add Elasticsearch APT repository
      ansible.builtin.apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
        filename: elastic-8.x
        state: present
        update_cache: yes

    - name: Install Elasticsearch package
      ansible.builtin.apt:
        name: elasticsearch
        state: present

    - name: Restart elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        state: restarted
        enabled: yes
