---
- name: Install and configure Kibana
  block:
    - name: Determine the host's internal IP address
      set_fact:
        host_interface_ip: "{{ ansible_all_ipv4_addresses | select('search', '^10\\.') | list | first }}"

    - name: Add Elastic APT repository
      ansible.builtin.apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
        filename: elastic-8.x
        state: present
        update_cache: yes

    - name: Setup Kibana package
      ansible.builtin.apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Configure Kibana settings
      ansible.builtin.template:
        src: config.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: '0644'

    - name: Restart and enable Kibana service
      ansible.builtin.systemd:
        name: kibana
        state: restarted
        enabled: yes
